import { Router } from 'express';
import addressRoutes from '@/routes/address.routes.js';
import adminRoutes from '@/routes/admin.routes.js';
import authRoutes from '@/routes/auth.routes.js';
import bookingRoutes from '@/routes/booking.routes.js';
import catalogRoutes from '@/routes/catalog.routes.js';
import customerRoutes from '@/routes/customer.routes.js';
import homeCarouselRoutes from '@/routes/home-carousel.routes.js';
import healthRoutes from '@/routes/health.routes.js';
import providerAvailabilityRoutes from '@/routes/provider-availability.routes.js';
import providerBookingRoutes from '@/routes/provider-booking.routes.js';
import providerUrgentRoutes from '@/routes/provider-urgent.routes.js';
import providerPostServiceRoutes from '@/routes/provider-post-service.routes.js';
import postServiceRoutes from '@/routes/post-service.routes.js';
import invoiceReviewRoutes from '@/routes/invoice-review.routes.js';
import filesRoutes from '@/routes/files.routes.js';
import homeHealthRoutes from '@/routes/home-health.routes.js';
import { assetsRouter, roomsRouter, warrantiesRouter } from '@/routes/assets.routes.js';
import maintenanceSchedulesRoutes from '@/routes/maintenance-schedules.routes.js';
import favouriteRoutes from '@/routes/favourite.routes.js';
import assetTypesRoutes from '@/routes/asset-types.routes.js';
import providerHomeHealthRoutes from '@/routes/provider-home-health.routes.js';
import providerQualityRoutes from '@/routes/provider-quality.routes.js';
import homeInvitationsRoutes from '@/routes/home-invitations.routes.js';
import { trustedRouter } from '@/routes/home-members.routes.js';
import discoveryRoutes from '@/routes/discovery.routes.js';
import operationsRoutes from '@/routes/operations.routes.js';
import operationsProviderRoutes from '@/routes/operations-provider.routes.js';
import carePlansRoutes from '@/routes/care-plans.routes.js';
import organizationsRoutes from '@/routes/organizations.routes.js';
import intelligenceRoutes from '@/routes/intelligence.routes.js';
import marketplaceRoutes from '@/routes/marketplace.routes.js';
import iotRoutes from '@/routes/iot.routes.js';
import networkRoutes from '@/routes/network.routes.js';
import trustRoutes from '@/routes/trust.routes.js';
import financeRoutes from '@/routes/finance.routes.js';
import customerLifecycleRoutes from '@/routes/customer-lifecycle.routes.js';
import securityRoutes from '@/routes/security.routes.js';
import privacyRoutes from '@/routes/privacy.routes.js';
import globalizationRoutes from '@/routes/globalization.routes.js';
import notificationRoutes from '@/routes/notification.routes.js';
import urgentRoutes from '@/routes/urgent.routes.js';
import paymentRoutes from '@/routes/payment.routes.js';
import providerRoutes from '@/routes/provider.routes.js';
import appVersionRoutes from '@/routes/app-version.routes.js';
import homeHelpRoutes from '@/routes/home-help.routes.js';
import platformRoutes from '@/routes/platform.routes.js';

const router = Router();

router.use('/platform', platformRoutes);
router.use('/app', appVersionRoutes);
router.use('/home-help', homeHelpRoutes);
router.use('/health', healthRoutes);
router.use('/home-carousel', homeCarouselRoutes);
router.use('/auth', authRoutes);
router.use('/customers', customerRoutes);
router.use('/providers', providerRoutes);
router.use('/providers', providerAvailabilityRoutes);
router.use('/provider', providerBookingRoutes);
router.use('/provider', providerUrgentRoutes);
router.use('/provider', providerPostServiceRoutes);
router.use('/provider', providerHomeHealthRoutes);
router.use('/provider', providerQualityRoutes);
router.use('/provider', operationsProviderRoutes);
router.use('/home-invitations', homeInvitationsRoutes);
router.use('/trusted-contacts', trustedRouter);
router.use('/homes', homeHealthRoutes);
router.use('/assets', assetsRouter);
router.use('/rooms', roomsRouter);
router.use('/warranties', warrantiesRouter);
router.use('/maintenance-schedules', maintenanceSchedulesRoutes);
router.use('/favourite-providers', favouriteRoutes);
router.use('/asset-types', assetTypesRoutes);
router.use('/bookings', bookingRoutes);
router.use('/', paymentRoutes);
router.use('/bookings', postServiceRoutes);
router.use('/urgent-requests', urgentRoutes);
router.use('/notifications', notificationRoutes);
router.use('/', invoiceReviewRoutes);
router.use('/files', filesRoutes);
router.use('/admin', adminRoutes);
router.use('/', addressRoutes);
router.use('/', catalogRoutes);
router.use('/', discoveryRoutes);
router.use('/', operationsRoutes);
router.use('/', carePlansRoutes);
router.use('/', organizationsRoutes);
router.use('/', intelligenceRoutes);
router.use('/', marketplaceRoutes);
router.use('/', iotRoutes);
router.use('/', networkRoutes);
router.use('/', trustRoutes);
router.use('/', financeRoutes);
router.use('/', customerLifecycleRoutes);
router.use('/security', securityRoutes);
router.use('/privacy', privacyRoutes);
router.use('/', globalizationRoutes);

export default router;
