/** Phase 19 — Finance & Business Intelligence */

export interface Money {
  amountMinor: number;
  currency: string;
}

export const DEFAULT_CURRENCY = 'INR';

export enum FinancialEventType {
  PAYMENT_COLLECTED = 'PAYMENT_COLLECTED',
  PAYMENT_AUTHORIZED = 'PAYMENT_AUTHORIZED',
  PAYMENT_CAPTURED = 'PAYMENT_CAPTURED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',
  SERVICE_REVENUE = 'SERVICE_REVENUE',
  MARKETPLACE_REVENUE = 'MARKETPLACE_REVENUE',
  PART_REVENUE = 'PART_REVENUE',
  DISCOUNT = 'DISCOUNT',
  COUPON_COST = 'COUPON_COST',
  GATEWAY_FEE = 'GATEWAY_FEE',
  PROVIDER_EARNING = 'PROVIDER_EARNING',
  PROVIDER_COMMISSION = 'PROVIDER_COMMISSION',
  PROVIDER_PAYOUT = 'PROVIDER_PAYOUT',
  PAYOUT_REVERSAL = 'PAYOUT_REVERSAL',
  REFUND = 'REFUND',
  GUARANTEE_COST = 'GUARANTEE_COST',
  CLAIM_COST = 'CLAIM_COST',
  SUBSCRIPTION_REVENUE = 'SUBSCRIPTION_REVENUE',
  TAX_LIABILITY = 'TAX_LIABILITY',
  ADJUSTMENT = 'ADJUSTMENT',
}

export enum FinancialEventStatus {
  PENDING = 'PENDING',
  POSTED = 'POSTED',
  REVERSED = 'REVERSED',
  FAILED = 'FAILED',
}

export enum FinancialDirection {
  INFLOW = 'INFLOW',
  OUTFLOW = 'OUTFLOW',
  NEUTRAL = 'NEUTRAL',
}

export enum FinancialSourceType {
  BOOKING = 'BOOKING',
  PAYMENT = 'PAYMENT',
  REFUND = 'REFUND',
  PAYOUT = 'PAYOUT',
  MARKETPLACE_ORDER = 'MARKETPLACE_ORDER',
  SUBSCRIPTION = 'SUBSCRIPTION',
  ORGANIZATION_INVOICE = 'ORGANIZATION_INVOICE',
  CLAIM = 'CLAIM',
  ADJUSTMENT = 'ADJUSTMENT',
  MANUAL = 'MANUAL',
}

export enum ReconciliationStatus {
  MATCHED = 'MATCHED',
  PARTIAL = 'PARTIAL',
  MISMATCH = 'MISMATCH',
  PENDING = 'PENDING',
}

export enum FinancialAlertSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum FinancialAlertStatus {
  OPEN = 'OPEN',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  INVESTIGATING = 'INVESTIGATING',
  RESOLVED = 'RESOLVED',
  FALSE_POSITIVE = 'FALSE_POSITIVE',
}

export enum ForecastConfidence {
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
}

export enum LtvType {
  REALIZED = 'REALIZED',
  PREDICTED = 'PREDICTED',
}

export enum FinanceApprovalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXECUTED = 'EXECUTED',
}

export enum FinanceAdminRole {
  FINANCE_VIEWER = 'FINANCE_VIEWER',
  FINANCE_OPERATOR = 'FINANCE_OPERATOR',
  FINANCE_MANAGER = 'FINANCE_MANAGER',
  FINANCE_ADMIN = 'FINANCE_ADMIN',
}

export enum FinancialAdjustmentType {
  CREDIT = 'CREDIT',
  DEBIT = 'DEBIT',
}
