export enum HomeCapability {
  HOME_VIEW = 'HOME_VIEW',
  HOME_EDIT = 'HOME_EDIT',
  HOME_MEMBER_INVITE = 'HOME_MEMBER_INVITE',
  HOME_MEMBER_REMOVE = 'HOME_MEMBER_REMOVE',
  ASSET_VIEW = 'ASSET_VIEW',
  ASSET_EDIT = 'ASSET_EDIT',
  BOOKING_CREATE = 'BOOKING_CREATE',
  BOOKING_VIEW = 'BOOKING_VIEW',
  BOOKING_PAY = 'BOOKING_PAY',
  BOOKING_CANCEL = 'BOOKING_CANCEL',
  BOOKING_TRACK = 'BOOKING_TRACK',
  BOOKING_PARTICIPATE = 'BOOKING_PARTICIPATE',
  DEVICE_VIEW = 'DEVICE_VIEW',
  DEVICE_MANAGE = 'DEVICE_MANAGE',
  DEVICE_ALERT_ACK = 'DEVICE_ALERT_ACK',
}

export enum HomeMemberRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
  VIEWER = 'VIEWER',
}

export enum HomeMemberStatus {
  ACTIVE = 'ACTIVE',
  INVITED = 'INVITED',
  REMOVED = 'REMOVED',
}

export enum HomeInvitationStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  REVOKED = 'REVOKED',
  EXPIRED = 'EXPIRED',
}

export enum HomeMemberActivityType {
  MEMBER_INVITED = 'MEMBER_INVITED',
  INVITATION_ACCEPTED = 'INVITATION_ACCEPTED',
  MEMBER_REMOVED = 'MEMBER_REMOVED',
  ROLE_CHANGED = 'ROLE_CHANGED',
}

export enum HomeNotificationEventType {
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  PROVIDER_EN_ROUTE = 'PROVIDER_EN_ROUTE',
  PROVIDER_ARRIVED = 'PROVIDER_ARRIVED',
  SERVICE_STARTED = 'SERVICE_STARTED',
  SERVICE_COMPLETED = 'SERVICE_COMPLETED',
  IOT_CRITICAL_ALERT = 'IOT_CRITICAL_ALERT',
  IOT_DEVICE_OFFLINE = 'IOT_DEVICE_OFFLINE',
  IOT_MAINTENANCE_INSIGHT = 'IOT_MAINTENANCE_INSIGHT',
}

export enum BookingParticipantRole {
  BOOKER = 'BOOKER',
  PAYER = 'PAYER',
  RECIPIENT = 'RECIPIENT',
  OBSERVER = 'OBSERVER',
}

export enum BookingParticipantPermission {
  VIEW_BOOKING = 'VIEW_BOOKING',
  TRACK_PROVIDER = 'TRACK_PROVIDER',
  PAY = 'PAY',
  VIEW_INVOICE = 'VIEW_INVOICE',
  RATE_SERVICE = 'RATE_SERVICE',
  REPORT_ISSUE = 'REPORT_ISSUE',
  CONFIRM_COMPLETION = 'CONFIRM_COMPLETION',
  CONTACT_PROVIDER = 'CONTACT_PROVIDER',
}
