/** Phase 23 — Scale, Performance & Architecture Optimization */

export enum IndexRecommendationStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  APPLIED = 'APPLIED',
}

export enum LoadTestStatus {
  DRAFT = 'DRAFT',
  SCHEDULED = 'SCHEDULED',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum PerformanceRegressionStatus {
  OPEN = 'OPEN',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  RESOLVED = 'RESOLVED',
}

export enum PerformanceRegressionSeverity {
  WARNING = 'WARNING',
  CRITICAL = 'CRITICAL',
}

export enum CapacityRiskLevel {
  NORMAL = 'NORMAL',
  WARNING = 'WARNING',
  CRITICAL = 'CRITICAL',
}

export enum PerformanceBudgetMetric {
  API_P95_MS = 'API_P95_MS',
  API_P99_MS = 'API_P99_MS',
  ERROR_RATE = 'ERROR_RATE',
  DB_QUERY_P95_MS = 'DB_QUERY_P95_MS',
  CACHE_HIT_RATE = 'CACHE_HIT_RATE',
  QUEUE_LAG_MS = 'QUEUE_LAG_MS',
  MOBILE_COLD_START_MS = 'MOBILE_COLD_START_MS',
  BUNDLE_SIZE_KB = 'BUNDLE_SIZE_KB',
  MEMORY_MB = 'MEMORY_MB',
  CPU_PERCENT = 'CPU_PERCENT',
}

export enum LoadTestScenarioType {
  NORMAL_BOOKING = 'NORMAL_BOOKING',
  URGENT_BURST = 'URGENT_BURST',
  PROVIDER_ACCEPTANCE_RACE = 'PROVIDER_ACCEPTANCE_RACE',
  PAYMENT_WEBHOOK_SPIKE = 'PAYMENT_WEBHOOK_SPIKE',
  MORNING_PEAK = 'MORNING_PEAK',
  NOTIFICATION_BURST = 'NOTIFICATION_BURST',
  ADMIN_ANALYTICS = 'ADMIN_ANALYTICS',
  LOCATION_UPDATES = 'LOCATION_UPDATES',
  CAMPAIGN_DELIVERY = 'CAMPAIGN_DELIVERY',
  ORG_BULK_BOOKING = 'ORG_BULK_BOOKING',
}
