import {
  BookingStatus,
  ErrorCode,
  MaintenanceScheduleStatus,
  WarrantyStatus,
} from '@ghaarfix/shared-types';
import { Booking } from '@/models/Booking.js';
import { HomeAsset } from '@/models/HomeAsset.js';
import { AssetServiceRecord } from '@/models/AssetServiceRecord.js';
import { MaintenanceSchedule } from '@/models/MaintenanceSchedule.js';
import { MaintenanceTemplate } from '@/models/MaintenanceTemplate.js';
import { ServiceCompletion } from '@/models/ServiceCompletion.js';
import { AppError } from '@/utils/AppError.js';
import type { IHomeAsset } from '@/models/HomeAsset.js';

export async function createAssetServiceRecordFromBooking(bookingId: string): Promise<void> {
  const existing = await AssetServiceRecord.findOne({ bookingId });
  if (existing) return;

  const booking = await Booking.findById(bookingId);
  if (!booking || booking.status !== BookingStatus.COMPLETED || !booking.assetId) return;

  const completion = await ServiceCompletion.findOne({ bookingId });
  const asset = await HomeAsset.findById(booking.assetId);
  if (!asset) return;

  const performedAt = booking.updatedAt;
  let nextMaintenanceDate: Date | undefined;

  const template = await MaintenanceTemplate.findOne({
    assetTypeId: asset.assetTypeId,
    serviceId: booking.serviceId,
    isActive: true,
  });
  if (template) {
    nextMaintenanceDate = new Date(performedAt.getTime() + template.intervalDays * 24 * 60 * 60 * 1000);
    await upsertMaintenanceSchedule(asset, template, performedAt, nextMaintenanceDate);
  }

  await AssetServiceRecord.create({
    assetId: booking.assetId,
    bookingId: booking._id,
    serviceId: booking.serviceId,
    providerId: booking.providerId,
    serviceType: booking.serviceSnapshot.name,
    summary: completion?.summary ?? 'Service completed',
    parts: completion?.parts ?? [],
    cost: booking.price.finalAmount,
    performedAt,
    nextMaintenanceDate,
  });
}

async function upsertMaintenanceSchedule(
  asset: IHomeAsset,
  template: InstanceType<typeof MaintenanceTemplate>,
  completedAt: Date,
  nextDueAt: Date,
) {
  await MaintenanceSchedule.findOneAndUpdate(
    { assetId: asset._id, templateId: template._id },
    {
      $set: {
        homeId: asset.homeId,
        customerId: asset.customerId,
        title: template.title,
        lastCompletedAt: completedAt,
        nextDueAt,
        status: MaintenanceScheduleStatus.UPCOMING,
        autoGenerated: true,
        snoozedUntil: null,
        skipReason: null,
      },
    },
    { upsert: true, new: true },
  );
}

export async function generateMaintenanceSchedulesForAsset(asset: IHomeAsset): Promise<void> {
  const templates = await MaintenanceTemplate.find({ assetTypeId: asset.assetTypeId, isActive: true });
  const baseDate = asset.installedAt ?? asset.createdAt;

  for (const template of templates) {
    const exists = await MaintenanceSchedule.findOne({ assetId: asset._id, templateId: template._id });
    if (exists) continue;

    const nextDueAt = new Date(baseDate.getTime() + template.intervalDays * 24 * 60 * 60 * 1000);
    await MaintenanceSchedule.create({
      assetId: asset._id,
      homeId: asset.homeId,
      customerId: asset.customerId,
      templateId: template._id,
      title: template.title,
      nextDueAt,
      status: MaintenanceScheduleStatus.UPCOMING,
      autoGenerated: true,
    });
  }
}

export async function refreshMaintenanceScheduleStatuses(): Promise<number> {
  const now = new Date();
  let count = 0;

  const schedules = await MaintenanceSchedule.find({
    status: { $in: [MaintenanceScheduleStatus.UPCOMING, MaintenanceScheduleStatus.DUE, MaintenanceScheduleStatus.OVERDUE] },
  });

  for (const schedule of schedules) {
    if (schedule.snoozedUntil && schedule.snoozedUntil > now) continue;

    const dueAt = schedule.nextDueAt;
    let nextStatus = MaintenanceScheduleStatus.UPCOMING;
    if (dueAt <= now) nextStatus = MaintenanceScheduleStatus.DUE;
    if (dueAt < new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000)) {
      nextStatus = MaintenanceScheduleStatus.OVERDUE;
    }

    if (schedule.status !== nextStatus) {
      schedule.status = nextStatus;
      await schedule.save();
      count += 1;
    }
  }
  return count;
}

export async function listHomeMaintenance(customerId: string, homeId: string) {
  const { getOwnedHome } = await import('@/modules/home-health/helpers.js');
  await getOwnedHome(customerId, homeId);
  await refreshMaintenanceScheduleStatuses();

  const schedules = await MaintenanceSchedule.find({ homeId, customerId }).sort({ nextDueAt: 1 });
  return schedules.map((s) => ({
    id: s._id.toString(),
    assetId: s.assetId.toString(),
    title: s.title,
    nextDueAt: s.nextDueAt.toISOString(),
    status: s.status,
    snoozedUntil: s.snoozedUntil?.toISOString(),
    lastCompletedAt: s.lastCompletedAt?.toISOString(),
  }));
}

export async function snoozeMaintenance(
  customerId: string,
  scheduleId: string,
  days: number,
) {
  const schedule = await MaintenanceSchedule.findOne({ _id: scheduleId, customerId });
  if (!schedule) throw new AppError('Schedule not found.', 404, ErrorCode.NOT_FOUND);
  schedule.snoozedUntil = new Date(Date.now() + days * 24 * 60 * 60 * 1000);
  await schedule.save();
  return { id: schedule._id.toString(), snoozedUntil: schedule.snoozedUntil.toISOString() };
}

export async function skipMaintenance(customerId: string, scheduleId: string, reason?: string) {
  const schedule = await MaintenanceSchedule.findOne({ _id: scheduleId, customerId });
  if (!schedule) throw new AppError('Schedule not found.', 404, ErrorCode.NOT_FOUND);
  schedule.status = MaintenanceScheduleStatus.SKIPPED;
  schedule.skipReason = reason;
  await schedule.save();
  return { id: schedule._id.toString(), status: schedule.status };
}

export async function completeMaintenanceSchedule(customerId: string, scheduleId: string) {
  const schedule = await MaintenanceSchedule.findOne({ _id: scheduleId, customerId });
  if (!schedule) throw new AppError('Schedule not found.', 404, ErrorCode.NOT_FOUND);
  const template = await MaintenanceTemplate.findById(schedule.templateId);
  const now = new Date();
  schedule.lastCompletedAt = now;
  schedule.status = MaintenanceScheduleStatus.COMPLETED;
  if (template) {
    schedule.nextDueAt = new Date(now.getTime() + template.intervalDays * 24 * 60 * 60 * 1000);
    schedule.status = MaintenanceScheduleStatus.UPCOMING;
  }
  await schedule.save();
  return { id: schedule._id.toString(), nextDueAt: schedule.nextDueAt.toISOString() };
}

export async function processMaintenanceReminders(): Promise<number> {
  await refreshMaintenanceScheduleStatuses();
  const { notifyBookingEvent } = await import('@/modules/notifications/notification.service.js');
  const { ReminderLog } = await import('@/models/ReminderLog.js');

  const now = new Date();
  let sent = 0;
  const schedules = await MaintenanceSchedule.find({
    status: { $in: [MaintenanceScheduleStatus.UPCOMING, MaintenanceScheduleStatus.DUE, MaintenanceScheduleStatus.OVERDUE] },
    $or: [{ snoozedUntil: null }, { snoozedUntil: { $lte: now } }],
  });

  for (const schedule of schedules) {
    const daysUntil = Math.ceil((schedule.nextDueAt.getTime() - now.getTime()) / (24 * 60 * 60 * 1000));
    let reminderType: string | null = null;
    if (daysUntil <= 0) reminderType = 'DUE_TODAY';
    else if (daysUntil <= 7) reminderType = 'DUE_7_DAYS';
    else if (daysUntil <= 30) reminderType = 'DUE_30_DAYS';
    if (!reminderType) continue;

    const logged = await ReminderLog.findOne({
      entityType: 'MAINTENANCE',
      entityId: schedule._id,
      reminderType,
    });
    if (logged) continue;

    await notifyBookingEvent(
      schedule.customerId.toString(),
      'MAINTENANCE_REMINDER',
      'Maintenance reminder',
      `${schedule.title} — ${reminderType.replace(/_/g, ' ').toLowerCase()}`,
      schedule.assetId.toString(),
    );
    await ReminderLog.create({
      customerId: schedule.customerId,
      entityType: 'MAINTENANCE',
      entityId: schedule._id,
      reminderType,
    });
    sent += 1;
  }
  return sent;
}

export async function processWarrantyAlerts(): Promise<number> {
  const { notifyBookingEvent } = await import('@/modules/notifications/notification.service.js');
  const { ReminderLog } = await import('@/models/ReminderLog.js');
  const { Warranty } = await import('@/models/Warranty.js');

  const now = new Date();
  let sent = 0;
  const warranties = await Warranty.find({
    status: { $in: [WarrantyStatus.ACTIVE, WarrantyStatus.EXPIRING] },
    endDate: { $gte: now },
  });

  for (const warranty of warranties) {
    const daysUntil = Math.ceil((warranty.endDate.getTime() - now.getTime()) / (24 * 60 * 60 * 1000));
    let reminderType: string | null = null;
    if (daysUntil <= 7) reminderType = 'WARRANTY_7_DAYS';
    else if (daysUntil <= 30) reminderType = 'WARRANTY_30_DAYS';
    else if (daysUntil <= 90) reminderType = 'WARRANTY_90_DAYS';

    if (daysUntil <= 30) {
      warranty.status = WarrantyStatus.EXPIRING;
      await warranty.save();
    }

    if (!reminderType) continue;

    const logged = await ReminderLog.findOne({
      entityType: 'WARRANTY',
      entityId: warranty._id,
      reminderType,
    });
    if (logged) continue;

    await notifyBookingEvent(
      warranty.customerId.toString(),
      'WARRANTY_ALERT',
      'Warranty expiring soon',
      `Warranty expires in ${daysUntil} days`,
      warranty.assetId.toString(),
    );
    await ReminderLog.create({
      customerId: warranty.customerId,
      entityType: 'WARRANTY',
      entityId: warranty._id,
      reminderType,
    });
    sent += 1;
  }
  return sent;
}
