import mongoose, { type Document, Schema, Types } from 'mongoose';
import { MaintenanceScheduleStatus } from '@ghaarfix/shared-types';

export interface IMaintenanceSchedule extends Document {
  assetId: Types.ObjectId;
  homeId: Types.ObjectId;
  customerId: Types.ObjectId;
  templateId: Types.ObjectId;
  title: string;
  lastCompletedAt?: Date;
  nextDueAt: Date;
  status: MaintenanceScheduleStatus;
  autoGenerated: boolean;
  snoozedUntil?: Date;
  skipReason?: string;
  createdAt: Date;
  updatedAt: Date;
}

const maintenanceScheduleSchema = new Schema<IMaintenanceSchedule>(
  {
    assetId: { type: Schema.Types.ObjectId, ref: 'HomeAsset', required: true, index: true },
    homeId: { type: Schema.Types.ObjectId, ref: 'Home', required: true, index: true },
    customerId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    templateId: { type: Schema.Types.ObjectId, ref: 'MaintenanceTemplate', required: true },
    title: { type: String, required: true },
    lastCompletedAt: { type: Date },
    nextDueAt: { type: Date, required: true, index: true },
    status: {
      type: String,
      enum: Object.values(MaintenanceScheduleStatus),
      default: MaintenanceScheduleStatus.UPCOMING,
      index: true,
    },
    autoGenerated: { type: Boolean, default: true },
    snoozedUntil: { type: Date },
    skipReason: { type: String, maxlength: 500 },
  },
  { timestamps: true },
);

maintenanceScheduleSchema.index({ homeId: 1, status: 1, nextDueAt: 1 });

export const MaintenanceSchedule = mongoose.model<IMaintenanceSchedule>(
  'MaintenanceSchedule',
  maintenanceScheduleSchema,
);
